name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run lint
      run: |
        brew install swiftlint || true
        swiftlint
    - name: Build Release
      run: swift build -c release
    - name: Test (TSan)
      run: swift test --sanitize thread
