name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Run lint
      run: swiftlint
    - name: Build Release
      run: swift build -c release
    - name: Test (TSan)
      run: swift test --sanitize thread
